CREATE TABLE TBL_CATEGORIES(
	CATEGORYID UNIQUEIDENTIFIER,
	[NAME] NVARCHAR(50),
	CONSTRAINT PK_CATEGORYID PRIMARY KEY NONCLUSTERED(
		CATEGORYID ASC
	) ON [PRIMARY],
	CONSTRAINT UQ_NAME UNIQUE NONCLUSTERED(
		[NAME] ASC
	)ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE TBL_CATEGORIES ADD CONSTRAINT DF_CATEGORIES_CATEGORYID DEFAULT (NEWID()) FOR CATEGORYID

INSERT INTO TBL_CATEGORIES (NAME) 
VALUES
	('Action'),
	('Horror'),
	('Drama'),
	('Comedy'),
	('Fantasy')