CREATE TABLE TBL_MOVIES(
	MOVIEID UNIQUEIDENTIFIER NOT NULL,
	[NAME] NVARCHAR(50),
	[DESCRITPION] NVARCHAR(100),
	CATEGORYID UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_MOVIEID PRIMARY KEY NONCLUSTERED(
		MOVIEID ASC
	) ON [PRIMARY],
	CONSTRAINT UQ_NAME_DESCRIPTION_CATEGORYID UNIQUE NONCLUSTERED(
		[NAME] ASC,
		[DESCRITPION] ASC,
		CATEGORYID ASC
	)ON [PRIMARY]
)ON [PRIMARY]

ALTER TABLE TBL_MOVIES ADD CONSTRAINT DF_TBL_MOVIE_MOVIEID DEFAULT (NEWID()) FOR MOVIEID
ALTER TABLE TBL_MOVIES ADD CONSTRAINT FK_TBL_MOVIE_CATEGORYID FOREIGN KEY (CATEGORYID) REFERENCES TBL_CATEGORIES(CATEGORYID)