//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enriquez_Jomiel_MOVIE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MOVIES
    {
        public System.Guid MOVIEID { get; set; }
        public string NAME { get; set; }
        public string DESCRITPION { get; set; }
        public System.Guid CATEGORYID { get; set; }
    
        public virtual TBL_CATEGORIES TBL_CATEGORIES { get; set; }
    }
}
